### ISSUE TITLE
Typo in the repo description

### ISSUE THREAD

**Issue by Alexey-T** [Warfley/ObjPasUtils#1]
“ fucntions for FPC/Lazarus”

**Comment by Warfley** [comment]
Thank you

**Comment by Alexey-T** [comment]
IMO 'LazBaseUtils' is misleading ... it's not std laz package. Better RecUtilsEx, RecBaseUtils.

**Comment by Warfley** [comment]
I wanted to get away from the Rec (as this was formerly the RecUtils package, which was experimenting with record based types), because it is not just records, but now with the new Iterator library it also makes a lot of use of classes.

I will think about other names, maybe ObjPasUtils or something like that...
